apiVersion: batch/v1
kind: Job
metadata:
  name: agent-job-{{JOB_ID}}
  labels:
    app: coding-agent
spec:
  template:
    metadata:
      labels:
        app: coding-agent
    spec:
      containers:
      - name: agent
        image: agent-coding:latest
        command: ["/usr/local/bin/agent_entrypoint.sh"]
        args: ["{{TASK}}"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8888  # Jupyter
        - containerPort: 6080  # noVNC
        - containerPort: 5900  # VNC
      restartPolicy: Never
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace-pvc-{{JOB_ID}}
  backoffLimit: 2
  activeDeadlineSeconds: 3600  # 1 hour timeout
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-pvc-{{JOB_ID}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 